AirQualityMonitor: MainWindow Class Reference
MainWindow Class Reference
The main window of the AirQualityMonitor application.
#include <mainwindow.h>
Public Member Functions
MainWindow (QWidget *parent=nullptr)
Constructor for MainWindow.
double calculateDistance (double lat1, double lon1, double lat2, double lon2)
Calculates the distance between two geographic points.
void analyzeMeasurements (const QList< Measurement > &measurements)
Analyzes a list of measurements and updates the analysis text.
Private Slots
void onStationsFetched (const QList< Station > &stations)
Handles the stationsFetched signal from AirQualityManager.
void onStationClicked (QListWidgetItem *item)
Handles station selection from the station list widget.
void onSensorsFetched (const QList< Sensor > &sensors)
Handles the sensorsFetched signal from AirQualityManager.
void onSensorClicked (QListWidgetItem *item)
Handles sensor selection from the sensor list widget.
void onMeasurementsFetched (const QList< Measurement > &measurements)
Handles the measurementsFetched signal from AirQualityManager.
void onSearchTextChanged (const QString &text)
Filters stations based on search text input.
void onFindStationsInRadiusClicked ()
Initiates search for stations within a specified radius.
void onCoordinatesFetched (double latitude, double longitude)
Handles the coordinatesFetched signal from AirQualityManager.
void onSaveDataClicked ()
Saves current data to JSON files.
void onErrorOccurred (const QString &error)
Handles errors from AirQualityManager.
void onPeriodChanged (const QString &period)
Updates the chart based on the selected time period.
void onShowMapClicked ()
Displays the map widget.
void onStationSelectedFromMap (int stationId)
Handles station selection from the map widget.
Private Member Functions
void saveStationsToJson (const QList< Station > &stations)
Saves stations to a JSON file.
void saveSensorsToJson (const QList< Sensor > &sensors)
Saves sensors to a JSON file.
void saveMeasurementsToJson (const QList< Measurement > &measurements)
Saves measurements to a JSON file.
QList< Station > loadStationsFromJson ()
Loads stations from a JSON file.
QList< Sensor > loadSensorsFromJson ()
Loads sensors from a JSON file.
QList< Measurement > loadMeasurementsFromJson ()
Loads measurements from a JSON file.
void updateChart (const QList< Measurement > &measurements)
Updates the measurement chart with new data.
void loadOfflineData ()
Loads offline data from JSON files.
Private Attributes
QLineEdit * searchLineEdit
Line edit for searching stations.
QLineEdit * addressLineEdit
Line edit for entering address for radius search.
QLineEdit * radiusLineEdit
Line edit for entering radius in kilometers.
QPushButton * findStationsButton
Button to trigger radius-based station search.
QPushButton * saveDataButton
Button to save data to JSON.
QPushButton * showMapButton
Button to display the map.
QListWidget * stationListWidget
List widget for displaying stations.
QListWidget * sensorListWidget
List widget for displaying sensors.
QListWidget * measurementListWidget
List widget for displaying measurements.
QTextEdit * analysisTextEdit
Text edit for displaying measurement analysis.
QComboBox * periodComboBox
Combo box for selecting time period.
QChartView * chartView
Chart view for displaying measurement data.
QLineSeries * series
Line series for the chart.
AirQualityManager * aqManager
Manager for fetching air quality data.
QList< Station > stations
List of all stations.
QList< Station > filteredStations
List of filtered stations based on search.
QList< Sensor > sensors
List of sensors for the selected station.
QList< Measurement > measurements
List of measurements for the selected sensor.
QMap< int, QList< Sensor > > offlineSensors
Offline sensor data.
QMap< int, QList< Measurement > > offlineMeasurements
Offline measurement data.
Detailed Description
The main window of the AirQualityMonitor application.
Manages the user interface, including station selection, sensor data display, measurement charts, and map visualization. Interacts with AirQualityManager to fetch and process air quality data.
Definition at line 33 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (QWidget * parent = nullptr)
Constructor for MainWindow.
Parameters
parent Parent widget, defaults to nullptr.
parent Parent widget, defaults to nullptr.
Initializes the UI components, sets up connections, and fetches initial station data.
Definition at line 29 of file mainwindow.cpp.
References addressLineEdit, analysisTextEdit, aqManager, chartView, AirQualityManager::coordinatesFetched(), AirQualityManager::errorOccurred(), findStationsButton, loadOfflineData(), measurementListWidget, AirQualityManager::measurementsFetched(), onCoordinatesFetched(), onErrorOccurred(), onFindStationsInRadiusClicked(), onMeasurementsFetched(), onPeriodChanged(), onSaveDataClicked(), onSearchTextChanged(), onSensorClicked(), onSensorsFetched(), onShowMapClicked(), onStationClicked(), onStationsFetched(), periodComboBox, radiusLineEdit, saveDataButton, searchLineEdit, sensorListWidget, AirQualityManager::sensorsFetched(), series, showMapButton, stationListWidget, and AirQualityManager::stationsFetched().
Member Function Documentation
analyzeMeasurements()
void MainWindow::analyzeMeasurements (const QList< Measurement > & measurements)
Analyzes a list of measurements and updates the analysis text.
Parameters
measurements List of measurements to analyze.
References measurements, and stations.
Referenced by onStationClicked().
calculateDistance()
double MainWindow::calculateDistance (double lat1, double lon1, double lat2, double lon2)
Calculates the distance between two geographic points.
Parameters
lat1 Latitude of the first point in degrees.
lon1 Longitude of the first point in degrees.
lat2 Latitude of the second point in degrees.
lon2 Longitude of the second point in degrees.
Returns
Distance in kilometers.
Referenced by onStationClicked().
loadMeasurementsFromJson()
QList< Measurement > MainWindow::loadMeasurementsFromJson () private
Loads measurements from a JSON file.
Returns
List of loaded measurements.
Referenced by onStationClicked().
loadOfflineData()
void MainWindow::loadOfflineData () private
Loads offline data from JSON files.
Referenced by MainWindow(), and onStationClicked().
loadSensorsFromJson()
QList< Sensor > MainWindow::loadSensorsFromJson () private
Loads sensors from a JSON file.
Returns
List of loaded sensors.
Referenced by onStationClicked().
loadStationsFromJson()
QList< Station > MainWindow::loadStationsFromJson () private
Loads stations from a JSON file.
Returns
List of loaded stations.
Referenced by onStationClicked().
onCoordinatesFetched
void MainWindow::onCoordinatesFetched (double latitude, double longitude) private slot
Handles the coordinatesFetched signal from AirQualityManager.
Parameters
latitude Latitude of the fetched coordinates.
longitude Longitude of the fetched coordinates.
Referenced by MainWindow(), and onStationClicked().
onErrorOccurred
void MainWindow::onErrorOccurred (const QString & error) private slot
Handles errors from AirQualityManager.
Parameters
error Error message.
Referenced by MainWindow(), and onStationClicked().
onFindStationsInRadiusClicked
void MainWindow::onFindStationsInRadiusClicked () private slot
Initiates search for stations within a specified radius.
Referenced by MainWindow(), and onStationClicked().
onMeasurementsFetched
void MainWindow::onMeasurementsFetched (const QList< Measurement > & measurements) private slot
Handles the measurementsFetched signal from AirQualityManager.
Parameters
measurements List of fetched measurements.
References measurements.
Referenced by MainWindow(), and onStationClicked().
onPeriodChanged
void MainWindow::onPeriodChanged (const QString & period) private slot
Updates the chart based on the selected time period.
Parameters
period Selected time period.
Referenced by MainWindow(), and onStationClicked().
onSaveDataClicked
void MainWindow::onSaveDataClicked () private slot
Saves current data to JSON files.
Referenced by MainWindow(), and onStationClicked().
onSearchTextChanged
void MainWindow::onSearchTextChanged (const QString & text) private slot
Filters stations based on search text input.
Parameters
text Search text entered by the user.
Referenced by MainWindow(), and onStationClicked().
onSensorClicked
void MainWindow::onSensorClicked (QListWidgetItem * item) private slot
Handles sensor selection from the sensor list widget.
Parameters
item Selected list item.
Referenced by MainWindow(), and onStationClicked().
onSensorsFetched
void MainWindow::onSensorsFetched (const QList< Sensor > & sensors) private slot
Handles the sensorsFetched signal from AirQualityManager.
Parameters
sensors List of fetched sensors.
References sensors.
Referenced by MainWindow(), and onStationClicked().
onShowMapClicked
void MainWindow::onShowMapClicked () private slot
Displays the map widget.
Displays the map widget with station markers.
Definition at line 123 of file mainwindow.cpp.
References aqManager, filteredStations, offlineMeasurements, onStationSelectedFromMap(), and MapWidget::stationSelected().
Referenced by MainWindow().
onStationClicked
void MainWindow::onStationClicked (QListWidgetItem * item) private slot
Handles station selection from the station list widget.
Fetches sensors for the selected station.
Parameters
item Selected list item.
item Selected station item.
Updates the sensor list with fetched sensors.
Parameters
sensorsList List of fetched sensors.
Fetches measurements for the selected sensor.
Parameters
item Selected sensor item.
Updates the measurement list and chart with fetched measurements.
Parameters
measurementsList List of fetched measurements.
Filters stations based on search text.
Parameters
text Search text.
Initiates a radius-based station search.
Filters stations within the specified radius using fetched coordinates.
Parameters
latitude Latitude of the center point.
longitude Longitude of the center point.
Saves current data to JSON files.
Handles errors and loads offline data.
Parameters
error Error message.
Updates the chart when the time period changes.
Parameters
period Selected time period.
Calculates the distance between two geographic points using the Haversine formula.
Parameters
lat1 Latitude of the first point in degrees.
lon1 Longitude of the first point in degrees.
lat2 Latitude of the second point in degrees.
lon2 Longitude of the second point in degrees.
Returns
Distance in kilometers.
Analyzes measurements and updates the analysis text edit.
Parameters
measurements List of measurements to analyze.
Saves stations to a JSON file.
Parameters
stations List of stations to save.
Saves sensors to a JSON file.
Parameters
sensors List of sensors to save.
Saves measurements to a JSON file.
Parameters
measurements List of measurements to save.
Loads stations from a JSON file.
Returns
List of loaded stations.
Loads sensors from a JSON file.
Returns
List of loaded sensors.
Loads measurements from a JSON file.
Returns
List of loaded measurements.
Updates the chart with measurement data for the selected period.
Parameters
measurements List of measurements to display.
Loads offline data from JSON files into memory.
Definition at line 178 of file mainwindow.cpp.
References addressLineEdit, analysisTextEdit, analyzeMeasurements(), aqManager, calculateDistance(), chartView, Measurement::dateTime, filteredStations, Sensor::id, Station::id, Station::latitude, loadMeasurementsFromJson(), loadOfflineData(), loadSensorsFromJson(), loadStationsFromJson(), Station::longitude, measurementListWidget, measurements, Station::name, offlineMeasurements, offlineSensors, onCoordinatesFetched(), onErrorOccurred(), onFindStationsInRadiusClicked(), onMeasurementsFetched(), onPeriodChanged(), onSaveDataClicked(), onSearchTextChanged(), onSensorClicked(), onSensorsFetched(), Measurement::paramName, Sensor::paramName, periodComboBox, radiusLineEdit, saveMeasurementsToJson(), saveSensorsToJson(), saveStationsToJson(), sensorListWidget, sensors, series, Measurement::stationId, Sensor::stationId, stationListWidget, stations, updateChart(), and Measurement::value.
Referenced by MainWindow(), and onStationSelectedFromMap().
onStationSelectedFromMap
void MainWindow::onStationSelectedFromMap (int stationId) private slot
Handles station selection from the map widget.
Parameters
stationId ID of the selected station.
Definition at line 136 of file mainwindow.cpp.
References filteredStations, onStationClicked(), and stationListWidget.
Referenced by onShowMapClicked().
onStationsFetched
void MainWindow::onStationsFetched (const QList< Station > & stationsList) private slot
Handles the stationsFetched signal from AirQualityManager.
Updates the station list with fetched stations.
Parameters
stations List of fetched stations.
stationsList List of fetched stations.
Definition at line 151 of file mainwindow.cpp.
References filteredStations, offlineMeasurements, saveStationsToJson(), stationListWidget, and stations.
Referenced by MainWindow().
saveMeasurementsToJson()
void MainWindow::saveMeasurementsToJson (const QList< Measurement > & measurements) private
Saves measurements to a JSON file.
Parameters
measurements List of measurements to save.
References measurements.
Referenced by onStationClicked().
saveSensorsToJson()
void MainWindow::saveSensorsToJson (const QList< Sensor > & sensors) private
Saves sensors to a JSON file.
Parameters
sensors List of sensors to save.
References sensors.
Referenced by onStationClicked().
saveStationsToJson()
void MainWindow::saveStationsToJson (const QList< Station > & stations) private
Saves stations to a JSON file.
Parameters
stations List of stations to save.
References stations.
Referenced by onStationClicked(), and onStationsFetched().
updateChart()
void MainWindow::updateChart (const QList< Measurement > & measurements) private
Updates the measurement chart with new data.
Parameters
measurements List of measurements to display.
References measurements.
Referenced by onStationClicked().
Member Data Documentation
addressLineEdit
QLineEdit* MainWindow::addressLineEdit private
Line edit for entering address for radius search.
Definition at line 185 of file mainwindow.h.
Referenced by MainWindow(), and onStationClicked().
analysisTextEdit
QTextEdit* MainWindow::analysisTextEdit private
Text edit for displaying measurement analysis.
Definition at line 193 of file mainwindow.h.
Referenced by MainWindow(), and onStationClicked().
aqManager
AirQualityManager* MainWindow::aqManager private
Manager for fetching air quality data.
Definition at line 197 of file mainwindow.h.
Referenced by MainWindow(), onShowMapClicked(), and onStationClicked().
chartView
QChartView* MainWindow::chartView private
Chart view for displaying measurement data.
Definition at line 195 of file mainwindow.h.
Referenced by MainWindow(), and onStationClicked().
filteredStations
QList<Station> MainWindow::filteredStations private
List of filtered stations based on search.
Definition at line 200 of file mainwindow.h.
Referenced by onShowMapClicked(), onStationClicked(), onStationSelectedFromMap(), and onStationsFetched().
findStationsButton
QPushButton* MainWindow::findStationsButton private
Button to trigger radius-based station search.
Definition at line 187 of file mainwindow.h.
Referenced by MainWindow().
measurementListWidget
QListWidget* MainWindow::measurementListWidget private
List widget for displaying measurements.
Definition at line 192 of file mainwindow.h.
Referenced by MainWindow(), and onStationClicked().
measurements
QList<Measurement> MainWindow::measurements private
List of measurements for the selected sensor.
Definition at line 202 of file mainwindow.h.
Referenced by analyzeMeasurements(), onMeasurementsFetched(), onStationClicked(), saveMeasurementsToJson(), and updateChart().
offlineMeasurements
QMap<int, QList<Measurement> > MainWindow::offlineMeasurements private
Offline measurement data.
Definition at line 204 of file mainwindow.h.
Referenced by onShowMapClicked(), onStationClicked(), and onStationsFetched().
offlineSensors
QMap<int, QList<Sensor> > MainWindow::offlineSensors private
Offline sensor data.
Definition at line 203 of file mainwindow.h.
Referenced by onStationClicked().
periodComboBox
QComboBox* MainWindow::periodComboBox private
Combo box for selecting time period.
Definition at line 194 of file mainwindow.h.
Referenced by MainWindow(), and onStationClicked().
radiusLineEdit
QLineEdit* MainWindow::radiusLineEdit private
Line edit for entering radius in kilometers.
Definition at line 186 of file mainwindow.h.
Referenced by MainWindow(), and onStationClicked().
saveDataButton
QPushButton* MainWindow::saveDataButton private
Button to save data to JSON.
Definition at line 188 of file mainwindow.h.
Referenced by MainWindow().
searchLineEdit
QLineEdit* MainWindow::searchLineEdit private
Line edit for searching stations.
Definition at line 184 of file mainwindow.h.
Referenced by MainWindow().
sensorListWidget
QListWidget* MainWindow::sensorListWidget private
List widget for displaying sensors.
Definition at line 191 of file mainwindow.h.
Referenced by MainWindow(), and onStationClicked().
sensors
QList<Sensor> MainWindow::sensors private
List of sensors for the selected station.
Definition at line 201 of file mainwindow.h.
Referenced by onSensorsFetched(), onStationClicked(), and saveSensorsToJson().
series
QLineSeries* MainWindow::series private
Line series for the chart.
Definition at line 196 of file mainwindow.h.
Referenced by MainWindow(), and onStationClicked().
showMapButton
QPushButton* MainWindow::showMapButton private
Button to display the map.
Definition at line 189 of file mainwindow.h.
Referenced by MainWindow().
stationListWidget
QListWidget* MainWindow::stationListWidget private
List widget for displaying stations.
Definition at line 190 of file mainwindow.h.
Referenced by MainWindow(), onStationClicked(), onStationSelectedFromMap(), and onStationsFetched().
stations
QList<Station> MainWindow::stations private
List of all stations.
Definition at line 199 of file mainwindow.h.
Referenced by analyzeMeasurements(), onStationClicked(), onStationsFetched(), and saveStationsToJson().
The documentation for this class was generated from the following files:
mainwindow.h
mainwindow.cpp