/**
 * @file mainwindow.cpp
 * @brief Implementation of the MainWindow class.
 * @author Generated by Grok
 * @date 2025-04-22
 *
 * Contains the implementation of the MainWindow class, handling the user interface
 * and interactions with the AirQualityManager.
 */

#include "MainWindow.h"
#include "MapWidget.h"
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QMessageBox>
#include <cmath>
#include <QFile>
#include <QJsonDocument>
#include <QJsonArray>
#include <QJsonObject>
#include <algorithm>

/**
 * @brief Constructor for MainWindow.
 * @param parent Parent widget, defaults to nullptr.
 *
 * Initializes the UI components, sets up connections, and fetches initial station data.
 */
MainWindow::MainWindow(QWidget *parent) : QMainWindow(parent) {
    QWidget *central = new QWidget(this);
    setCentralWidget(central);

    resize(800, 600);

    searchLineEdit = new QLineEdit(this);
    searchLineEdit->setPlaceholderText("Wpisz nazwę miejscowości...");

    addressLineEdit = new QLineEdit(this);
    addressLineEdit->setPlaceholderText("Wpisz adres (np. Polanka 3, Poznań)...");

    radiusLineEdit = new QLineEdit(this);
    radiusLineEdit->setPlaceholderText("Wpisz promień w km...");

    findStationsButton = new QPushButton("Znajdź stacje w promieniu", this);
    saveDataButton = new QPushButton("Zapisz dane do JSON", this);
    showMapButton = new QPushButton("Pokaż mapę", this);

    stationListWidget = new QListWidget(this);
    sensorListWidget = new QListWidget(this);
    measurementListWidget = new QListWidget(this);
    analysisTextEdit = new QTextEdit(this);
    analysisTextEdit->setReadOnly(true);
    analysisTextEdit->setFixedHeight(100);
    analysisTextEdit->setObjectName("analysisTextEdit");

    periodComboBox = new QComboBox(this);
    periodComboBox->addItem("Ostatni dzień", 1);
    periodComboBox->addItem("Ostatni tydzień", 7);
    periodComboBox->addItem("Ostatni miesiąc", 30);

    series = new QLineSeries(this);
    QChart *chart = new QChart();
    chart->addSeries(series);
    chart->setTitle("Wykres pomiarów");

    QDateTimeAxis *axisX = new QDateTimeAxis(this);
    axisX->setTickCount(10);
    axisX->setFormat("yyyy-MM-dd HH:mm");
    axisX->setTitleText("Czas");
    chart->addAxis(axisX, Qt::AlignBottom);
    series->attachAxis(axisX);

    QValueAxis *axisY = new QValueAxis(this);
    axisY->setLabelFormat("%.1f");
    axisY->setTitleText("Wartość");
    chart->addAxis(axisY, Qt::AlignLeft);
    series->attachAxis(axisY);

    chartView = new QChartView(chart, this);
    chartView->setRenderHint(QPainter::Antialiasing);
    chartView->setMinimumHeight(300);

    aqManager = new AirQualityManager(this);

    auto *layout = new QVBoxLayout(central);
    layout->addWidget(searchLineEdit);

    auto *radiusLayout = new QHBoxLayout();
    radiusLayout->addWidget(addressLineEdit);
    radiusLayout->addWidget(radiusLineEdit);
    radiusLayout->addWidget(findStationsButton);
    radiusLayout->addWidget(saveDataButton);
    radiusLayout->addWidget(showMapButton);
    layout->addLayout(radiusLayout);

    layout->addWidget(stationListWidget);
    layout->addWidget(sensorListWidget);
    layout->addWidget(measurementListWidget);
    layout->addWidget(periodComboBox);
    layout->addWidget(chartView);
    layout->addWidget(analysisTextEdit);

    connect(searchLineEdit, &QLineEdit::textChanged, this, &MainWindow::onSearchTextChanged);
    connect(stationListWidget, &QListWidget::itemClicked, this, &MainWindow::onStationClicked);
    connect(sensorListWidget, &QListWidget::itemClicked, this, &MainWindow::onSensorClicked);
    connect(findStationsButton, &QPushButton::clicked, this, &MainWindow::onFindStationsInRadiusClicked);
    connect(saveDataButton, &QPushButton::clicked, this, &MainWindow::onSaveDataClicked);
    connect(showMapButton, &QPushButton::clicked, this, &MainWindow::onShowMapClicked);
    connect(aqManager, &AirQualityManager::stationsFetched, this, &MainWindow::onStationsFetched);
    connect(aqManager, &AirQualityManager::sensorsFetched, this, &MainWindow::onSensorsFetched);
    connect(aqManager, &AirQualityManager::measurementsFetched, this, &MainWindow::onMeasurementsFetched);
    connect(aqManager, &AirQualityManager::coordinatesFetched, this, &MainWindow::onCoordinatesFetched);
    connect(aqManager, &AirQualityManager::errorOccurred, this, &MainWindow::onErrorOccurred);
    connect(periodComboBox, &QComboBox::currentTextChanged, this, &MainWindow::onPeriodChanged);

    aqManager->fetchStations();
    loadOfflineData();
}

/**
 * @brief Displays the map widget with station markers.
 */
void MainWindow::onShowMapClicked() {
    QMap<int, QList<Measurement>> onlineMeasurements = aqManager->getOnlineMeasurements();
    MapWidget *mapWidget = new MapWidget(filteredStations, offlineMeasurements, onlineMeasurements, this);
    mapWidget->setWindowTitle("Mapa stacji pomiarowych");
    mapWidget->resize(800, 600);
    connect(mapWidget, &MapWidget::stationSelected, this, &MainWindow::onStationSelectedFromMap);
    mapWidget->show();
}

/**
 * @brief Handles station selection from the map widget.
 * @param stationId ID of the selected station.
 */
void MainWindow::onStationSelectedFromMap(int stationId) {
    for (int i = 0; i < filteredStations.size(); ++i) {
        if (filteredStations[i].id == stationId) {
            stationListWidget->setCurrentRow(i);
            onStationClicked(stationListWidget->item(i));
            activateWindow();
            break;
        }
    }
}

/**
 * @brief Updates the station list with fetched stations.
 * @param stationsList List of fetched stations.
 */
void MainWindow::onStationsFetched(const QList<Station> &stationsList) {
    stations = stationsList;
    stationListWidget->clear();
    filteredStations.clear();

    for (const auto &s : stations) {
        filteredStations.append(s);
    }

    std::sort(filteredStations.begin(), filteredStations.end(), [](const Station &a, const Station &b) {
        return a.name.toLower() < b.name.toLower();
    });

    for (const auto &s : filteredStations) {
        QString itemText = s.name;
        if (offlineMeasurements.contains(s.id)) {
            itemText += " (dane offline dostępne)";
        }
        stationListWidget->addItem(itemText);
    }
    saveStationsToJson(stations);
}

/**
 * @brief Fetches sensors for the selected station.
 * @param item Selected station item.
 */
void MainWindow::onStationClicked(QListWidgetItem *item) {
    int index = stationListWidget->row(item);
    if (index >= 0 && index < filteredStations.size()) {
        Station station = filteredStations[index];
        sensorListWidget->clear();
        measurementListWidget->clear();
        analysisTextEdit->clear();
        series->clear();
        if (offlineMeasurements.contains(station.id)) {
            sensors = offlineSensors[station.id];
            measurements = offlineMeasurements[station.id];
            for (const auto &s : sensors) {
                sensorListWidget->addItem(s.paramName);
女士
        } else {
            aqManager->fetchSensors(station.id);
        }
    }
}

/**
 * @brief Updates the sensor list with fetched sensors.
 * @param sensorsList List of fetched sensors.
 */
void MainWindow::onSensorsFetched(const QList<Sensor> &sensorsList) {
    sensors = sensorsList;
    sensorListWidget->clear();
    measurementListWidget->clear();
    analysisTextEdit->clear();
    series->clear();

    for (const auto &s : sensors) {
        sensorListWidget->addItem(s.paramName);
    }
    saveSensorsToJson(sensors);
}

/**
 * @brief Fetches measurements for the selected sensor.
 * @param item Selected sensor item.
 */
void MainWindow::onSensorClicked(QListWidgetItem *item) {
    int index = sensorListWidget->row(item);
    if (index >= 0 && index < sensors.size()) {
        if (!measurements.isEmpty() && offlineMeasurements.contains(filteredStations[stationListWidget->currentRow()].id)) {
            updateChart(measurements);
            analyzeMeasurements(measurements);
            measurementListWidget->clear();
            for (const auto &m : measurements) {
                QString valueStr = (m.value >= 0) ? QString::number(m.value) : "brak";
                measurementListWidget->addItem(
                    QString("%1: %2 (%3)").arg(m.paramName).arg(valueStr).arg(m.dateTime.toString())
                    );
            }
        } else {
            aqManager->fetchSensorData(sensors[index].id);
        }
    }
}

/**
 * @brief Updates the measurement list and chart with fetched measurements.
 * @param measurementsList List of fetched measurements.
 */
void MainWindow::onMeasurementsFetched(const QList<Measurement> &measurementsList) {
    measurements = measurementsList;
    int stationId = filteredStations[stationListWidget->currentRow()].id;
    for (auto &m : measurements) {
        m.stationId = stationId;
    }
    measurementListWidget->clear();
    analysisTextEdit->clear();
    series->clear();

    if (measurements.isEmpty()) {
        measurementListWidget->addItem("Brak danych pomiarowych dla tego czujnika.");
    } else {
        for (const auto &m : measurements) {
            QString valueStr = (m.value >= 0) ? QString::number(m.value) : "brak";
            measurementListWidget->addItem(
                QString("%1: %2 (%3)").arg(m.paramName).arg(valueStr).arg(m.dateTime.toString())
                );
        }
        updateChart(measurements);
        analyzeMeasurements(measurements);
    }
    saveMeasurementsToJson(measurements);
}

/**
 * @brief Filters stations based on search text.
 * @param text Search text.
 */
void MainWindow::onSearchTextChanged(const QString &text) {
    stationListWidget->clear();
    filteredStations.clear();

    for (const auto &station : stations) {
        if (station.name.contains(text, Qt::CaseInsensitive)) {
            filteredStations.append(station);
        }
    }

    std::sort(filteredStations.begin(), filteredStations.end(), [](const Station &a, const Station &b) {
        return a.name.toLower() < b.name.toLower();
    });

    for (const auto &s : filteredStations) {
        QString itemText = s.name;
        if (offlineMeasurements.contains(s.id)) {
            itemText += " (dane offline dostępne)";
        }
        stationListWidget->addItem(itemText);
    }
}

/**
 * @brief Initiates a radius-based station search.
 */
void MainWindow::onFindStationsInRadiusClicked() {
    QString address = addressLineEdit->text().trimmed();
    QString radiusText = radiusLineEdit->text().trimmed();

    if (address.isEmpty() || radiusText.isEmpty()) {
        QMessageBox::warning(this, "Błąd", "Proszę podać adres i promień.");
        return;
    }

    bool ok;
    double radius = radiusText.toDouble(&ok);
    if (!ok || radius <= 0) {
        QMessageBox::warning(this, "Błąd", "Promień musi być liczbą dodatnią.");
        return;
    }

    aqManager->fetchCoordinates(address);
}

/**
 * @brief Filters stations within the specified radius using fetched coordinates.
 * @param latitude Latitude of the center point.
 * @param longitude Longitude of the center point.
 */
void MainWindow::onCoordinatesFetched(double latitude, double longitude) {
    double radius = radiusLineEdit->text().toDouble();

    stationListWidget->clear();
    filteredStations.clear();

    for (const auto &station : stations) {
        double distance = calculateDistance(latitude, longitude, station.latitude, station.longitude);
        if (distance <= radius) {
            filteredStations.append(station);
        }
    }

    std::sort(filteredStations.begin(), filteredStations.end(), [](const Station &a, const Station &b) {
        return a.name.toLower() < b.name.toLower();
    });

    for (const auto &s : filteredStations) {
        QString itemText = s.name;
        if (offlineMeasurements.contains(s.id)) {
            itemText += " (dane offline dostępne)";
        }
        stationListWidget->addItem(itemText);
    }

    if (filteredStations.isEmpty()) {
        stationListWidget->addItem("Brak stacji w zadanym promieniu.");
    }
}

/**
 * @brief Saves current data to JSON files.
 */
void MainWindow::onSaveDataClicked() {
    saveStationsToJson(stations);
    saveSensorsToJson(sensors);
    saveMeasurementsToJson(measurements);
    QMessageBox::information(this, "Sukces", "Dane zostały zapisane do plików JSON.");
}

/**
 * @brief Handles errors and loads offline data.
 * @param error Error message.
 */
void MainWindow::onErrorOccurred(const QString &error) {
    loadOfflineData();

    stationListWidget->clear();
    filteredStations.clear();
    sensorListWidget->clear();
    measurementListWidget->clear();
    analysisTextEdit->clear();
    series->clear();

    for (const auto &station : stations) {
        if (offlineMeasurements.contains(station.id)) {
            filteredStations.append(station);
        }
    }

    std::sort(filteredStations.begin(), filteredStations.end(), [](const Station &a, const Station &b) {
        return a.name.toLower() < b.name.toLower();
    });

    for (const auto &s : filteredStations) {
        QString itemText = s.name + " (dane offline dostępne)";
        stationListWidget->addItem(itemText);
    }

    if (filteredStations.isEmpty()) {
        QMessageBox::warning(this, "Błąd", "Brak połączenia z internetem: " + error + "\nBrak danych offline do wczytania.");
        stationListWidget->addItem("Brak stacji z danymi historycznymi.");
    }
}

/**
 * @brief Updates the chart when the time period changes.
 * @param period Selected time period.
 */
void MainWindow::onPeriodChanged(const QString &period) {
    if (!measurements.isEmpty()) {
        updateChart(measurements);
    }
}

/**
 * @brief Calculates the distance between two geographic points using the Haversine formula.
 * @param lat1 Latitude of the first point in degrees.
 * @param lon1 Longitude of the first point in degrees.
 * @param lat2 Latitude of the second point in degrees.
 * @param lon2 Longitude of the second point in degrees.
 * @return Distance in kilometers.
 */
double MainWindow::calculateDistance(double lat1, double lon1, double lat2, double lon2) {
    const double PI = 3.141592653589;
    const double R = 6371.0;

    lat1 = lat1 * PI / 180.0;
    lon1 = lon1 * PI / 180.0;
    lat2 = lat2 * PI / 180.0;
    lon2 = lon2 * PI / 180.0;

    double dLat = lat2 - lat1;
    double dLon = lon2 - lon1;

    double a = sin(dLat / 2.0) * sin(dLat / 2.0) +
               cos(lat1) * cos(lat2) * sin(dLon / 2.0) * sin(dLon / 2.0);
    double c = 2.0 * atan2(sqrt(a), sqrt(1.0 - a));
    double distance = R * c;

    return distance;
}

/**
 * @brief Analyzes measurements and updates the analysis text edit.
 * @param measurements List of measurements to analyze.
 */
void MainWindow::analyzeMeasurements(const QList<Measurement> &measurements) {
    if (measurements.isEmpty()) {
        analysisTextEdit->setText("Brak danych do analizy.");
        return;
    }

    double minValue = measurements.first().value;
    double maxValue = measurements.first().value;
    QDateTime minDateTime = measurements.first().dateTime;
    QDateTime maxDateTime = measurements.first().dateTime;
    double sum = 0.0;
    int validCount = 0;

    for (const auto &m : measurements) {
        if (m.value >= 0) {
            if (m.value < minValue) {
                minValue = m.value;
                minDateTime = m.dateTime;
            }
            if (m.value > maxValue) {
                maxValue = m.value;
                maxDateTime = m.dateTime;
            }
            sum += m.value;
            validCount++;
        }
    }

    double average = (validCount > 0) ? sum / validCount : 0.0;

    double trend = 0.0;
    if (validCount > 1) {
        double sumX = 0.0, sumY = 0.0, sumpXY = 0.0, sumXX = 0.0;
        int i = 0;
        for (const auto &m : measurements) {
            if (m.value >= 0) {
                double x = i;
                double y = m.value;
                sumX += x;
                sumY += y;
                sumXY += x * y;
                sumXX += x * x;
                i++;
            }
        }
        double n = validCount;
        trend = (n * sumXY - sumX * sumY) / (n * sumXX - sumX * sumX);
    }

    QString analysisText = "Analiza danych:\n";
    analysisText += QString("Najmniejsza wartość: %1 (%2)\n").arg(minValue).arg(minDateTime.toString());
    analysisText += QString("Największa wartość: %1 (%2)\n").arg(maxValue).arg(maxDateTime.toString());
    analysisText += QString("Średnia wartość: %1\n").arg(average, 0, 'f', 2);
    analysisText += "Trend: ";
    if (trend > 0) {
        analysisText += "Rosnący";
    } else if (trend < 0) {
        analysisText += "Malejący";
    } else {
        analysisText += "Stabilny";
    }

    analysisTextEdit->setText(analysisText);
}

/**
 * @brief Saves stations to a JSON file.
 * @param stations List of stations to save.
 */
void MainWindow::saveStationsToJson(const QList<Station> &stations) {
    QJsonArray stationsArray;
    for (const auto &s : stations) {
        QJsonObject stationObj;
        stationObj["id"] = s.id;
        stationObj["name"] = s.name;
        stationObj["latitude"] = s.latitude;
        stationObj["longitude"] = s.longitude;
        stationsArray.append(stationObj);
    }

    QJsonDocument doc(stationsArray);
    QFile file("stations.json");
    if (file.open(QIODevice::WriteOnly)) {
        file.write(doc.toJson());
        file.close();
    } else {
        QMessageBox::warning(this, "Błąd", "Nie udało się zapisać stacji do pliku JSON.");
    }
}

/**
 * @brief Saves sensors to a JSON file.
 * @param sensors List of sensors to save.
 */
void MainWindow::saveSensorsToJson(const QList<Sensor> &sensors) {
    QJsonArray sensorsArray;
    int stationId = filteredStations[stationListWidget->currentRow()].id;
    for (const auto &s : sensors) {
        QJsonObject sensorObj;
        sensorObj["stationId"] = stationId;
        sensorObj["id"] = s.id;
        sensorObj["paramName"] = s.paramName;
        sensorsArray.append(sensorObj);
    }

    QJsonDocument doc(sensorsArray);
    QFile file("sensors.json");
    if (file.open(QIODevice::WriteOnly)) {
        file.write(doc.toJson());
        file.close();
    } else {
        QMessageBox::warning(this, "Błąd", "Nie udało się zapisać sensorów do pliku JSON.");
    }
}

/**
 * @brief Saves measurements to a JSON file.
 * @param measurements List of measurements to save.
 */
void MainWindow::saveMeasurementsToJson(const QList<Measurement> &measurements) {
    QJsonArray measurementsArray;
    int stationId = filteredStations[stationListWidget->currentRow()].id;
    for (const auto &m : measurements) {
        QJsonObject measurementObj;
        measurementObj["stationId"] = stationId;
        measurementObj["paramName"] = m.paramName;
        measurementObj["value"] = m.value;
        measurementObj["dateTime"] = m.dateTime.toString(Qt::ISODate);
        measurementsArray.append(measurementObj);
    }

    QJsonDocument doc(measurementsArray);
    QFile file("measurements.json");
    if (file.open(QIODevice::WriteOnly)) {
        file.write(doc.toJson());
        file.close();
    } else {
        QMessageBox::warning(this, "Błąd", "Nie udało się zapisać pomiarów do pliku JSON.");
    }
}

/**
 * @brief Loads stations from a JSON file.
 * @return List of loaded stations.
 */
QList<Station> MainWindow::loadStationsFromJson() {
    QList<Station> stations;
    QFile file("stations.json");
    if (file.open(QIODevice::ReadOnly)) {
        QJsonDocument doc = QJsonDocument::fromJson(file.readAll());
        QJsonArray arr = doc.array();
        for (const auto &v : arr) {
            QJsonObject obj = v.toObject();
            Station s;
            s.id = obj["id"].toInt();
            s.name = obj["name"].toString();
            s.latitude = obj["latitude"].toDouble();
            s.longitude = obj["longitude"].toDouble();
            stations.append(s);
        }
        file.close();
    }
    return stations;
}

/**
 * @brief Loads sensors from a JSON file.
 * @return List of loaded sensors.
 */
QList<Sensor> MainWindow::loadSensorsFromJson() {
    QList<Sensor> sensors;
    QFile file("sensors.json");
    if (file.open(QIODevice::ReadOnly)) {
        QJsonDocument doc = QJsonDocument::fromJson(file.readAll());
        QJsonArray arr = doc.array();
        for (const auto &v : arr) {
            QJsonObject obj = v.toObject();
            Sensor s;
            s.stationId = obj["stationId"].toInt();
            s.id = obj["id"].toInt();
            s.paramName = obj["paramName"].toString();
            sensors.append(s);
        }
        file.close();
    }
    return sensors;
}

/**
 * @brief Loads measurements from a JSON file.
 * @return List of loaded measurements.
 */
QList<Measurement> MainWindow::loadMeasurementsFromJson() {
    QList<Measurement> measurements;
    QFile file("measurements.json");
    if (file.open(QIODevice::ReadOnly)) {
        QJsonDocument doc = QJsonDocument::fromJson(file.readAll());
        QJsonArray arr = doc.array();
        for (const auto &v : arr) {
            QJsonObject obj = v.toObject();
            Measurement m;
            m.stationId = obj["stationId"].toInt();
            m.paramName = obj["paramName"].toString();
            m.value = obj["value"].toDouble();
            m.dateTime = QDateTime::fromString(obj["dateTime"].toString(), Qt::ISODate);
            measurements.append(m);
        }
        file.close();
    }
    return measurements;
}

/**
 * @brief Updates the chart with measurement data for the selected period.
 * @param measurements List of measurements to display.
 */
void MainWindow::updateChart(const QList<Measurement> &measurements) {
    series->clear();

    int days = periodComboBox->currentData().toInt();
    QDateTime now = QDateTime::currentDateTime();
    QDateTime cutoff = now.addDays(-days);

    double minValue = std::numeric_limits<double>::max();
    double maxValue = std::numeric_limits<double>::lowest();

    for (const auto &m : measurements) {
        if (m.value >= 0 && m.dateTime >= cutoff) {
            series->append(m.dateTime.toMSecsSinceEpoch(), m.value);
            minValue = qMin(minValue, m.value);
            maxValue = qMax(maxValue, m.value);
        }
    }

    if (series->count() > 0) {
        QChart *chart = chartView->chart();
        QDateTimeAxis *axisX = qobject_cast<QDateTimeAxis*>(chart->axisX());
        QValueAxis *axisY = qobject_cast<QValueAxis*>(chart->axisY());

        axisX->setRange(cutoff, now);
        axisY->setRange(minValue * 0.9, maxValue * 1.1);
        chart->setTitle("Wykres pomiarów: " + measurements.first().paramName);
    } else {
        chartView->chart()->setTitle("Brak danych dla wybranego okresu");
    }
}

/**
 * @brief Loads offline data from JSON files into memory.
 */
void MainWindow::loadOfflineData() {
    stations = loadStationsFromJson();
    QList<Sensor> loadedSensors = loadSensorsFromJson();
    QList<Measurement> loadedMeasurements = loadMeasurementsFromJson();

    offlineSensors.clear();
    offlineMeasurements.clear();

    for (const auto &s : loadedSensors) {
        int stationId = s.stationId;
        offlineSensors[stationId].append(s);
    }

    for (const auto &m : loadedMeasurements) {
        int stationId = m.stationId;
        offlineMeasurements[stationId].append(m);
    }
}