/**
 * @file main.cpp
 * @brief Main entry point for the AirQualityMonitor application.
 * @author Generated by Grok
 * @date 2025-04-22
 *
 * This file contains the main function that initializes the Qt application
 * and displays the main window.
 */

#include <QApplication>
#include "MainWindow.h"

/**
 * @brief Main function to start the AirQualityMonitor application.
 * @param argc Number of command-line arguments.
 * @param argv Array of command-line arguments.
 * @return Exit status of the application.
 *
 * Initializes the QApplication, creates and shows the MainWindow,
 * and starts the Qt event loop.
 */
int main(int argc, char *argv[]) {
    QApplication a(argc, argv);
    MainWindow w;
    w.show();
    return a.exec();
}