AirQualityMonitor: AirQualityManager Class Reference
AirQualityManager Class Reference
Manages fetching and storing air quality data from APIs.
#include <airqualitymanager.h>
Signals
void stationsFetched (const QList< Station > &stations)
Emitted when stations are successfully fetched.
void sensorsFetched (const QList< Sensor > &sensors)
Emitted when sensors are successfully fetched.
void measurementsFetched (const QList< Measurement > &measurements)
Emitted when measurements are successfully fetched.
void coordinatesFetched (double latitude, double longitude)
Emitted when coordinates are successfully fetched.
void errorOccurred (const QString &error)
Emitted when an error occurs during data fetching.
Public Member Functions
AirQualityManager (QObject *parent=nullptr)
Constructor for AirQualityManager.
void fetchStations ()
Fetches the list of all monitoring stations.
void fetchSensors (int stationId)
Fetches sensors for a specific station.
void fetchSensorData (int sensorId)
Fetches measurement data for a specific sensor.
void fetchCoordinates (const QString &address)
Fetches geographic coordinates for a given address.
QMap< int, QList< Measurement > > getOnlineMeasurements () const
Gets the current online measurements.
Private Attributes
QNetworkAccessManager * networkManager
Manages network requests.
QMap< int, QList< Measurement > > onlineMeasurements
Stores online measurements.
Detailed Description
Manages fetching and storing air quality data from APIs.
Provides methods to fetch stations, sensors, measurements, and coordinates, and emits signals when data is available or errors occur.
Definition at line 57 of file airqualitymanager.h.
Constructor & Destructor Documentation
AirQualityManager()
AirQualityManager::AirQualityManager (QObject * parent = nullptr) explicit
Constructor for AirQualityManager.
Parameters
parent Parent object, defaults to nullptr.
parent Parent object, defaults to nullptr.
Initializes the network manager for API requests.
Definition at line 24 of file airqualitymanager.cpp.
References networkManager.
Member Function Documentation
coordinatesFetched
void AirQualityManager::coordinatesFetched (double latitude, double longitude) signal
Emitted when coordinates are successfully fetched.
Parameters
latitude Latitude of the location.
longitude Longitude of the location.
Definition at line 228 of file moc_airqualitymanager.cpp.
Referenced by fetchCoordinates(), and MainWindow::MainWindow().
errorOccurred
void AirQualityManager::errorOccurred (const QString & error) signal
Emitted when an error occurs during data fetching.
Parameters
error Error message.
Definition at line 235 of file moc_airqualitymanager.cpp.
Referenced by fetchCoordinates(), fetchSensorData(), fetchSensors(), fetchStations(), and MainWindow::MainWindow().
fetchCoordinates()
void AirQualityManager::fetchCoordinates (const QString & address)
Fetches geographic coordinates for a given address.
Fetches geographic coordinates for an address using Nominatim API.
Parameters
address Address to geocode.
address Address to geocode.
Sends a GET request and emits coordinatesFetched or errorOccurred.
Definition at line 142 of file airqualitymanager.cpp.
References coordinatesFetched(), errorOccurred(), and networkManager.
fetchSensorData()
void AirQualityManager::fetchSensorData (int sensorId)
Fetches measurement data for a specific sensor.
Parameters
sensorId ID of the sensor.
sensorId ID of the sensor.
Sends a GET request to the GIOS API and emits measurementsFetched or errorOccurred.
Definition at line 94 of file airqualitymanager.cpp.
References Measurement::dateTime, errorOccurred(), measurementsFetched(), networkManager, onlineMeasurements, Measurement::paramName, Measurement::stationId, and Measurement::value.
fetchSensors()
void AirQualityManager::fetchSensors (int stationId)
Fetches sensors for a specific station.
Parameters
stationId ID of the station.
stationId ID of the station.
Sends a GET request to the GIOS API and emits sensorsFetched or errorOccurred.
Definition at line 64 of file airqualitymanager.cpp.
References errorOccurred(), Sensor::id, networkManager, Sensor::paramName, sensorsFetched(), and Sensor::stationId.
fetchStations()
void AirQualityManager::fetchStations ()
Fetches the list of all monitoring stations.
Fetches the list of all monitoring stations from the API.
Sends a GET request to the GIOS API and emits stationsFetched or errorOccurred.
Definition at line 33 of file airqualitymanager.cpp.
References errorOccurred(), Station::id, Station::latitude, Station::longitude, Station::name, networkManager, and stationsFetched().
getOnlineMeasurements()
QMap< int, QList< Measurement > > AirQualityManager::getOnlineMeasurements () const
Gets the current online measurements.
Returns
Map of station IDs to lists of measurements.
Definition at line 132 of file airqualitymanager.cpp.
References onlineMeasurements.
measurementsFetched
void AirQualityManager::measurementsFetched (const QList< Measurement > & measurements) signal
Emitted when measurements are successfully fetched.
Parameters
measurements List of fetched measurements.
Definition at line 221 of file moc_airqualitymanager.cpp.
Referenced by fetchSensorData(), and MainWindow::MainWindow().
sensorsFetched
void AirQualityManager::sensorsFetched (const QList< Sensor > & sensors) signal
Emitted when sensors are successfully fetched.
Parameters
sensors List of fetched sensors.
Definition at line 214 of file moc_airqualitymanager.cpp.
Referenced by fetchSensors(), and MainWindow::MainWindow().
stationsFetched
void AirQualityManager::stationsFetched (const QList< Station > & stations) signal
Emitted when stations are successfully fetched.
Parameters
stations List of fetched stations.
Definition at line 207 of file moc_airqualitymanager.cpp.
Referenced by fetchStations(), and MainWindow::MainWindow().
Member Data Documentation
networkManager
QNetworkAccessManager* AirQualityManager::networkManager private
Manages network requests.
Definition at line 129 of file airqualitymanager.h.
Referenced by AirQualityManager(), fetchCoordinates(), fetchSensorData(), fetchSensors(), and fetchStations().
onlineMeasurements
QMap<int, QList<Measurement> > AirQualityManager::onlineMeasurements private
Stores online measurements.
Definition at line 130 of file airqualitymanager.h.
Referenced by fetchSensorData(), and getOnlineMeasurements().
The documentation for this class was generated from the following files:
airqualitymanager.h
airqualitymanager.cpp
build/Desktop_Qt_6_8_3_MinGW_64_bit-Debug/AirQualityMonitor_autogen/EWIEGA46WW/moc_airqualitymanager.cpp
build/Desktop_Qt_6_8_3_MinGW_64_bit-Debug/AirQualityMonitorTests_autogen/EWIEGA46WW/moc_airqualitymanager.cpp
build/Desktop_Qt_6_8_3_MinGW_64_bit-Debug/qualiti_autogen/EWIEGA46WW/moc_airqualitymanager.cpp