AirQualityMonitor: MapWidget Class Reference
MapWidget Class Reference
Displays a map with air quality station markers.
#include <MapWidget.h>
Classes
struct StationMarker
Represents a station marker on the map.
Signals
void stationSelected (int stationId)
Emitted when a station is selected.
Public Member Functions
MapWidget (const QList< Station > &stations, const QMap< int, QList< Measurement > > &offlineMeasurements, const QMap< int, QList< Measurement > > &onlineMeasurements, QWidget *parent=nullptr)
Constructor for MapWidget.
Protected Member Functions
void paintEvent (QPaintEvent *event) override
Paints the map and station markers.
void mousePressEvent (QMouseEvent *event) override
Handles mouse clicks to select stations.
Private Slots
void onCloseMapClicked ()
Closes the map widget.
Private Member Functions
QPointF latLonToPixel (double latitude, double longitude)
Converts latitude and longitude to pixel coordinates.
void showStationInfo (const Station &station)
Displays information about a selected station.
QString analyzeMeasurementsByParameter (const QList< Measurement > &measurements)
Analyzes measurements by parameter.
void initializeMarkers (const QList< Station > &stations)
Initializes station markers.
Private Attributes
QList< StationMarker > markers
List of station markers.
QPixmap mapImage
Map image (poland_map.png).
QMap< int, QList< Measurement > > offlineMeasurements
Offline measurement data.
QMap< int, QList< Measurement > > onlineMeasurements
Online measurement data.
QPushButton * closeMapButton
Button to close the map.
QVBoxLayout * layout
Layout for the widget.
bool mapLoaded
Indicates if the map image was loaded.
Detailed Description
Displays a map with air quality station markers.
Allows users to interact with stations by clicking markers to view details.
Definition at line 23 of file MapWidget.h.
Constructor & Destructor Documentation
MapWidget()
MapWidget::MapWidget (const QList< Station > & stations, const QMap< int, QList< Measurement > > & offline, const QMap< int, QList< Measurement > > & online, QWidget * parent = nullptr) explicit
Constructor for MapWidget.
Parameters
stations List of stations to display.
offlineMeasurements Offline measurement data.
onlineMeasurements Online measurement data.
parent Parent widget, defaults to nullptr.
stations List of stations to display.
offline Offline measurement data.
online Online measurement data.
parent Parent widget, defaults to nullptr.
Initializes the map image, markers, and UI components.
Definition at line 27 of file MapWidget.cpp.
References closeMapButton, initializeMarkers(), layout, mapImage, mapLoaded, offlineMeasurements, onCloseMapClicked(), and onlineMeasurements.
Member Function Documentation
analyzeMeasurementsByParameter()
QString MapWidget::analyzeMeasurementsByParameter (const QList< Measurement > & measurements) private
Analyzes measurements by parameter.
Analyzes measurements by parameter and returns a formatted string.
Parameters
measurements List of measurements to analyze.
Returns
Formatted analysis string.
Definition at line 152 of file MapWidget.cpp.
initializeMarkers()
void MapWidget::initializeMarkers (const QList< Station > & stations) private
Initializes station markers.
Initializes station markers from the provided stations.
Parameters
stations List of stations to initialize.
Definition at line 234 of file MapWidget.cpp.
References latLonToPixel(), markers, MapWidget::StationMarker::position, and MapWidget::StationMarker::station.
Referenced by MapWidget().
latLonToPixel()
QPointF MapWidget::latLonToPixel (double latitude, double longitude) private
Converts latitude and longitude to pixel coordinates.
Converts latitude and longitude to pixel coordinates on the map.
Parameters
latitude Latitude in degrees.
longitude Longitude in degrees.
Returns
Pixel position on the map.
Definition at line 112 of file MapWidget.cpp.
References mapImage, and mapLoaded.
Referenced by initializeMarkers().
mousePressEvent()
void MapWidget::mousePressEvent (QMouseEvent * event) override protected
Handles mouse clicks to select stations.
Parameters
event Mouse event.
Definition at line 89 of file MapWidget.cpp.
References mapImage, mapLoaded, markers, and showStationInfo().
onCloseMapClicked
void MapWidget::onCloseMapClicked () private slot
Closes the map widget.
Definition at line 226 of file MapWidget.cpp.
Referenced by MapWidget().
paintEvent()
void MapWidget::paintEvent (QPaintEvent * event) override protected
Paints the map and station markers.
Parameters
event Paint event.
Definition at line 61 of file MapWidget.cpp.
References mapImage, mapLoaded, and markers.
showStationInfo()
void MapWidget::showStationInfo (const Station & station) private
Displays information about a selected station.
Displays a dialog with station information and option to view data.
Parameters
station The selected station.
Definition at line 133 of file MapWidget.cpp.
References Station::id, Station::name, and stationSelected().
Referenced by mousePressEvent().
stationSelected
void MapWidget::stationSelected (int stationId) signal
Emitted when a station is selected.
Parameters
stationId ID of the selected station.
Definition at line 151 of file moc_MapWidget.cpp.
Referenced by MainWindow::onShowMapClicked(), and showStationInfo().
Member Data Documentation
closeMapButton
QPushButton* MapWidget::closeMapButton private
Button to close the map.
Definition at line 106 of file MapWidget.h.
Referenced by MapWidget().
layout
QVBoxLayout* MapWidget::layout private
Layout for the widget.
Definition at line 107 of file MapWidget.h.
Referenced by MapWidget().
mapImage
QPixmap MapWidget::mapImage private
Map image (poland_map.png).
Definition at line 103 of file MapWidget.h.
Referenced by latLonToPixel(), MapWidget(), mousePressEvent(), and paintEvent().
mapLoaded
bool MapWidget::mapLoaded private
Indicates if the map image was loaded.
Definition at line 108 of file MapWidget.h.
Referenced by latLonToPixel(), MapWidget(), mousePressEvent(), and paintEvent().
markers
QList<StationMarker> MapWidget::markers private
List of station markers.
Definition at line 102 of file MapWidget.h.
Referenced by initializeMarkers(), mousePressEvent(), and paintEvent().
offlineMeasurements
QMap<int, QList<Measurement> > MapWidget::offlineMeasurements private
Offline measurement data.
Definition at line 104 of file MapWidget.h.
Referenced by MapWidget().
onlineMeasurements
QMap<int, QList<Measurement> > MapWidget::onlineMeasurements private
Online measurement data.
Definition at line 105 of file MapWidget.h.
Referenced by MapWidget().
The documentation for this class was generated from the following files:
MapWidget.h
build/Desktop_Qt_6_8_3_MinGW_64_bit-Debug/AirQualityMonitor_autogen/EWIEGA46WW/moc_MapWidget.cpp
build/Desktop_Qt_6_8_3_MinGW_64_bit-Debug/AirQualityMonitorTests_autogen/EWIEGA46WW/moc_MapWidget.cpp
MapWidget.cpp